### PR TITLE
GPS - Clear Signal Strength Data

### PR DESCRIPTION
**Pull request by gaelj**
Clear GPS_DATA arrays used by MSP_GPS_SV_INFO before filling them.

Fixes https://github.com/cleanflight/cleanflight-configurator/issues/78

### CODE REVIEW

**Comment by skaman82** [comment]
Wow that was quick! You are awsome 👍

**Comment by gaelj** [comment]
Thank you @skaman82. I've done a few others too yesterday. I'll be travelling the next few days. Will implement any required modifications/fixes end of next week.

**Comment by skaman82** [comment]
After some testing I have noticed somme issues:

- After disconnecting the GPS, and the the USB and reconnecting the FC to the configurator again I still can see all the previous data (no GPS connected) - maybe it should all be cleared on connect.
bildschirmfoto 2016-06-21 um 12 19 56

- After testing it right now something strange happened. The sat info bars are not displayed at all - tried reconnecting, rebooting the board, power-cycling... No bars - even in the released configurator (I chek my GPS later in ublox)
bildschirmfoto 2016-06-21 um 12 24 15

Some other thing (has nothing to do with this PR): I remember that a while ago GPS used to be recognized almost instantly on connection by the FC. Now I have to wait up to 20 seconds until the GPS icon lights up in the sensors section. @gaelj what can cause this?

**Comment by gaelj** [comment]
Hi @skaman82,
(1) My fix was indeed incomplete. The GUI part needed some work as well.
(2) I now have the same problem, and it is unrelated to this PR. Turns out even in gpspassthough mode to u-center, I was receving invalid frames (I checked all baudrates). I had to revert to cleanflight 1.12.1 to get valid GPS passthough frames again. Then it completely stopped sending frames. Reverted back to 1.13.0 and activated gps auto config (I normally turn it off), and that got it running again. One of the last things I did in u-center before the problems appeared was set the dynamic model to airborne 1G. Not sure if that's related.
(3) GPS and other sensors status are in the message MSP_STATUS, which is sent every 100ms, so it's probably Cleanflight-related as well.

**Comment by gaelj** [comment]
Although even now it's working again I still don't have any bars either... even in stock configurator.

I noticed in CF code that max message length is 328 while in my case (NEO 8 M) u-center shows some frames 352 long. Recompiling with just this change doesn't change anything though.

**Comment by skaman82** [comment]
@gaelj tested this again today. It works like it should! Also the sat bars are back (strange). Tested with CF 1.13

**Comment by gaelj** [comment]
What satellite receiver do you have ?
I couldn't really test yesterday's commit because I don't see any more at all. Did you do your test today with it ?
Thanks for your help on this, as usual !

**Comment by skaman82** [comment]
I am testing with a Beitian BN-180 GPS module. Same as yesterday.

**Pull request merged**
