### PR TITLE
Translation to French

### PR DESCRIPTION
**Pull request by gaelj**

### CODE REVIEW

**Comment by skaman82** [comment]
I know, it is great to have al localized version of Configurator. The main problem with localization files is that they are a big pain in the but when it comes to adding new stuff or changing things - and if the person adding a new feature don't speak french or taiwanese (for example), the quality of the language file gets typically rapidly poorer over time. Or new things just do't get translated or a forgotten completely. Thats why I personally don't believe this is going to be merged, but @hydra has to decide this.

**Comment by hydra** [comment]
integration with an online translation system is the answer here.

somethink like this:

https://tech.yandex.com/translate/

The idea being to delegate translation of the UI to the community and not to the developers.

**Comment by Floyer007** [comment]
So translations are not required?
I'd begun to create an German translation-file, too.

**Comment by hydra** [comment]
@gaelj @Floyer007 not at the moment no.   ideally we need a build system that can highlight the missing translations for each build and a tool to show changed original text between releases so that translators know what to update.  I think we need to put a build system in place before we attempt to tackle this.

**Pull request closed without merging**
