### PR TITLE
Add new OSD fields

### PR DESCRIPTION
**Pull request by rosek86**
- Temperature and speed from ESC
- Fields merged from betaflight

### CODE REVIEW

**Comment by rosek86** [comment]
Okay, I can do this but then my commit will not work. The order of fields would be incorrect and if one moves ESC fields, GPS_LAT and GPS_LON moves on a display. Is that all right?

**Comment by mikeller** [comment]
If you wait a bit, I can open a PR for the relevant changes from Betaflight, and you can rebase your changes after that one has been merged.

**Comment by rosek86** [comment]
Make sense 👍

**Comment by mikeller** [comment]
Done: #492

**Comment by hydra** [comment]
#492 was merged instead.

**Pull request closed without merging**
