### PR TITLE
Board type detection before flashing

### PR DESCRIPTION
**Pull request by MasterZap**
Okay so this is my first stab at https://github.com/cleanflight/cleanflight-configurator/issues/357 

I'm too stupid (= suck at JavaScript too much) to figure out how to make some kind of proper message telling the user he is using the wrong firmware.... so I just put it in the log... which is crappy. Something more visible should happen.

Lemme know what you think I should do about this....

### CODE REVIEW

**Comment by MasterZap** [comment]
To be clear, don't merge this as it is as of today. This code doesn't actually flash anything, I've commented out the flashing for testing purpouses :)

**Comment by skaman82** [comment]
@MasterZap Did you make some progress on this?

**Comment by gaelj** [comment]
Wouldn't it be even better to select the proper fw instead of telling the user he is using the wrong one ?

**Comment by skaman82** [comment]
@gaelj 1+

**Comment by skaman82** [comment]
So for example if you have a naze connected > show only naze relevant versions

**Comment by gaelj** [comment]
Eaxctly. If @MasterZap has not shown up by the time my LED strip stuff is finalised, I am willing to take this on.

**Comment by MasterZap** [comment]
Yeah so I'm stupid busy with other stuff so this has been kinda derailed, but feel free to use whatever can be (ab)used of my code.

The reason I (at first, at least) didn't do "detect first, only show the relevant" is that I found no clean/safe way to detect the board *before* you attempted to connect to it, since that point in time is when we are starting to send commands to the board.

You could, in principle, toss off a command to the board speculatively, and when (or if) its reply arrived, you would then thin down the list of targets only to the selected one.

The danger with that is if you are in bootloader mode, but I guess you could re-use the "no reboot sequence" switch so that when it is on, you do no detection? OR have a separate "detect board" switch.... whichever.

I think I won't have time to devote to this in any near term, whatever time I have I try to spend flying instead. So feel free to do whatever with this, I'm not actively working on it right now....

**Comment by hydra** [comment]
We still need this, but this needs to be thought out a bit better so we can do a proper solution.

I'm going to close this PR so we can track current issues.  This PR and conversation can serve as a reference for future discussions.

**Comment by MasterZap** [comment]
Fine with this. But feel free to steal any code snippets from this that may be useful :)

**Pull request closed without merging**
