### PR TITLE
jBox Tooltip implementation using i18n_title, instead of populating jBox: Content - reduces DOM element counts

### PR DESCRIPTION
**Pull request by tricopterY**
Replaces #298

### CODE REVIEW

**Comment by tricopterY** [comment]
@hydra - sorry I have a forked branch with some silly bits in one. But the PR is ok. I am shy of re-basing.

**Comment by hydra** [comment]
@tricopterY there were a couple of tooltips missed, see 3993af0d8cf43fdd6fbb4e242dbc7000cf0bcd1f

**Comment by hydra** [comment]
also, i forgot to squash the commits, never mind...

**Comment by tricopterY** [comment]
Thanks Dominic for the fix and merge. I got a snippet of you in your booth
in the UK Drones' Show.
Keep up the great work you are doing.

**Pull request merged**
