### PR TITLE
Translate the GUI into spanish language

### PR DESCRIPTION
**Pull request by McGiverGim**
Complete translation of the messages file into spanish. 

There was an abandoned PR trying to do this: https://github.com/cleanflight/cleanflight-configurator/pull/446

Some things:
- Everybody can collaborate in the translation, don't need coding knowledge. Only go to this URL: http://cleanflight.oneskyapp.com/  I can add all the languages that the community want to translate.
- I've translated all words (but roll, pitch and yaw, I think this three words are better understood in english). The community will tell if this is correct or is better to translate all or let some other words untranslated.
- Some strings were not in the messages file, so they're not translated. This can be solved progressively in futures PR. 
- I think there's a need for a PR to let the user select the language in the configurator. Maybe some spanish user prefer english, or in a future some language has bad quality and the user prefer english. And will be mandatory to let the user communicate issues (to speak all the same language). If this PR is approved I can try to make it.

Maybe we can try with spanish language as test, see how it works, if the community collaborates, if they are happy with this, etc. and then add other languages or remove this.

### CODE REVIEW

**Comment by McGiverGim** [comment]
@hydra if this is finally going to be merged, please take a message here before to sync the translation with the latest version in git. The time has passed and I'm prettty sure that there're new strings ready to be translated ;)

**Comment by mikeller** [comment]
@hydra: Awesome effort! I think this deserves to have a go.

**Comment by hydra** [comment]
@McGiverGim yes it would be good to review the translations that have been changed.  You can find them by looking at changes to the english messages file.

If the majority of the work has been completed then it's probably OK to merge it and then the spanish-speaking users will hopefully provide corrections.

**Comment by McGiverGim** [comment]
There is no need to review "manually" the english file, I will upload the new english file to the http://cleanflight.oneskyapp.com and it will detect the new and the modified texts. I will try to do it this weekend. 
I will update the PR then.

**Comment by McGiverGim** [comment]
@hydra I've take a look at the changes, and in the "master" branch there's no changes since the 9 july, so I think that this PR is ready to merge. Am I wrong?

**Comment by hydra** [comment]
great, merging.

**Pull request merged**
