### PR TITLE
Issue #218: Display GPS HDOP

### PR DESCRIPTION
**Pull request by gaelj**
Show in setup tab, GPS tab and logging

### CODE REVIEW

**Comment by skaman82** [comment]
Usually I get HDOP values in UCenter in between 7 and 1.8. In the Configurator it shows me the value of 315. Is there a decimal mistake or what is the scaling you are using?

**Comment by gaelj** [comment]
I'm writing the raw value... Any idea about how to scale it ?
If not I will give it some research.

**Comment by skaman82** [comment]
Personally i dont know. But maybe @digitalentity has some thoughts on this.

Von meinem iPhone gesendet

**Comment by digitalentity** [comment]
@skaman82 I'm not sure about Cleanflight code, but in INAV HDOP readings are correct. However INAV has heavily refactored GPS driver.

**Comment by skaman82** [comment]
any news on the scaling question? 
Some examples for usual HDOP values:

http://www.rcgroups.com/forums/attachment.php?attachmentid=7008832
http://4.bp.blogspot.com/-rClNLxc9l84/TrwDRfqzU_I/AAAAAAAAAaQ/NXOsHI3JTnI/s1600/Esempi_HDOP_Satelliti.png
https://www.researchgate.net/profile/Yolanda_Van_Heezik/publication/250926097/figure/fig2/AS:298132064751617@1448091631376/Figure-2-Mean-location-error-m-LE-6-SD-for-each-HDOP-value-Mean-location-error-m.png

**Comment by gaelj** [comment]
I noticed a few days ago that GPS HDOP got left behind in one of the recent CF code cleanups.
I'll have to re submit a PR before if PR here is to make any sense.
But thanks for the links @skaman82 I'l look into them.

**Comment by skaman82** [comment]
@gaelj if you a working on this you might have a look at this too: https://github.com/cleanflight/cleanflight-configurator/issues/78

**Comment by hydra** [comment]
I think this PR should first check if the firmware supports HDOP correctly before attemting to use the data.  perhaps an MSP API version check is suitable here.

Please create a new PR with any updated code.

I'm going to close this PR so we can track current issues.  This PR and conversation can serve as a reference for future discussions.

**Pull request closed without merging**
