### PR TITLE
Additional cli time for large text dumps

### PR DESCRIPTION
**Pull request by KiteAnton**
When restoring dump settings and pasting large texts into cli the FC is sometimes unable to keep up and some parameters is missed. Additional waiting time needed between each command. 
Also when pasting to switch profiles additional time is needed to allow FC to switch profile without loosing commands.

### CODE REVIEW

**Comment by gaelj** [comment]
@skaman82 it would be nice to merge this PR.

**Comment by skaman82** [comment]
Merging things is usually not to me. I do it occasionaly but only GUI related stuff only. @hydra hasn't yet commented on this... I merged this for now - it is easy enought to revert, if necessary.

**Comment by oleost** [comment]
Tried cbff88dd1b38b122c317c2d025cdc3de1e2fe924 into my forked iNav configurator. Still got lost lines when doing full restore. Works better for me to have 100ms delay on everything.

**Comment by hydra** [comment]
this is a fine short term solution.

**Pull request merged**
