### PR TITLE
Introduce gulp build system and ES6 transpiler

### PR DESCRIPTION
**Pull request by rbirkby**
Rationale
-------------
Without a build system, the current configurator has limited options with respect to unit tests, CI, static analysis (lint), transpiling etc.

I would appreciate any positive or negative comments.

Details
---------
This PR shows one possible way to achieve this. There are others.
It uses [gulp](http://gulpjs.com/) for build and [6to5](http://6to5.org/) for ES6 transpilation.

The bulk of the code has been moved into /app. Then a build step copies the contents to /dist while transpiling the JavaScript files from ES6 to ES5.

The readme has been updated with instructions on how to build. In summary:
 
```bash
npm install
gulp
```

Then instead of pointing Chrome at the root of the configurator repo, you need to point it to the dist directory.

Finally, it should be noted that I'm writing this while I wait for parts to arrive - so I don't even have a flight controller to test this with. It starts fine (without console errors), but I'm unable to test it further. I don't envisage issues.

Future enhancements
-----------------------------

Having a build system means that the following things become easier:

1. Mocha/Jasmine tests
2. eslint
3. ES6 modules
4. Easier publishing to the app store (eg creating a zip)
5. Much more work simplifying the codebase using ES6 features

### CODE REVIEW

**Comment by hydra** [comment]
Thanks for taking the time to do this, I have not looed at gulp before.  I will get some feedback from some other developers i know to see what they think.

**Comment by pieterv** [comment]
To make this change easier to merge its probably better to separate out the upgrades to ES6 features from the change for the build step. If you revert those changes then when the build step is added you can use a codemod to automate the upgrade, the ones found here should make it super easy: https://github.com/cpojer/js-codemod, it includes codemods for arrow functions and shorthand properties. Additional eslint now includes a lot of autofix rules which can automatically fix issues it finds once you have it setup.

Probably also worth upgrading to babel 6 here as well since that is a larger change over babel 5.

Not totally sure if glup is even needed for this project since the build step is so simple, you could add your babel conf to a [`.babelrc` file](http://babeljs.io/docs/usage/babelrc/) then update your package.json to include something simple like:
```
  "scripts": {
    "build": "rm -rf dist && babel src -d dist"
  },
```
Which you can run via `npm run build`.

I would really recommend taking the next step and using the ES6 modules as moving away from globals tends to help a lot with code maintainability and makes it much easier to use third party code :)

@hydra @rbirkby I'm happy to help with setup up any build infra this is something you want, I have had a lot of experience setting these kinds of systems up in the past.

**Comment by rbirkby** [comment]
Happy for you to take this on @pieterv, but there didn't seen much appetite for moving forward when I did this.

**Comment by pieterv** [comment]
@rbirkby oh I just realised this is from a year ago, I just came across this and thought it was from a few days ago :P No problem, no point pushing this forward if it's not something they think the project needs.

**Comment by hydra** [comment]
@rbirkby and @pieterv @gaelj @skaman82 @stronnag 

Yes, we want a build system!  Yes we want tests. Yes we want a clean reliable and tested codebase that's easy to work on and has separation between layers, unlike the current codebase where everything is mixed together.

At the time there someone else was working on using angular for the configurator which has it's own build system, however that never materialized and this was blocked by that.

I don't think the long term future of the configurator codebase is with jQuery and I would love to be using more modern technologies (like angular, etc) but it's a rather large job.

I would like to be using a well tested, easy to use and common build system, UI and unit test framework.  I'm open to suggestions on how to transition the codebase to something more modern.  every time I work on the current codebase it just feels like adding more dirty code to an already dirty codebase.  I would love it if another pair of developers (1 JS, 1 UI) took on ownership of the configurator codebase moving forwards, I would take a back-seat since my time is pretty much all firmware related these days.  Of course I will still contribute for new features, etc.

Who wants to take on the challenge?

**Comment by skaman82** [comment]
@hydra I am allways happy to help out with the graphics/UI stuff. If we have a JS dev who is brave enough to take this on, I am happy to assist.

Von meinem iPhone gesendet

**Comment by gaelj** [comment]
@hydra 
I would need to learn angularjs or any other solution.
On the other hand, I can offer time and motivation.
I'd be honored to take on the challenge :pray:

**Comment by hydra** [comment]
@gaelj ideally we need a developer who is already good at using the angularjs (or similar) otherwise we'll just end up with a codebase of code that would make an experienced developer say 'you should have done it like this' and other like-minded experts wouldn't be as happy working on the codebase.   Do you know of any experienced angular developers?  Currently I know that the angular framework has a good seperation of layers and is widely trusted, however there was a transition from angular 1 to 2 and there are some big changes.  Certainly we wouldn't want to use angular 2 without the backing of experienced angular developers and likewise we wouldn't want to use angular 1 without very good reasons.

**Comment by hydra** [comment]
I'm going to close this PR so we can track current issues.  This PR and conversation can serve as a reference for future discussions.

**Pull request closed without merging**
