### PR TITLE
Show gps home info

### PR DESCRIPTION
**Pull request by gaelj**
Setup tab: Home direction is shown as a red dot circling around the edge of the compass 
GPS tab: Show home coords & direction + map icon

### CODE REVIEW

**Comment by skaman82** [comment]
• Can you move all Home related info (dist to home and direct to home) in the GPS Home box? 
bildschirmfoto 2016-05-06 um 14 09 33

• I've just tested this: If I click the icon on the map I get YOUR Location = HOME Location coordinates.
In the GPS home area there still no coordinates: 
bildschirmfoto 2016-05-06 um 14 10 03

• The position marker on the map is a bit small

**Comment by skaman82** [comment]
sorry, totally forgot about this. Will review it again this weekend.

**Comment by gaelj** [comment]
Home location issue is not solved yet.

**Comment by hydra** [comment]
can someone complete this work?

I'm closing all old configurator PRs so we can better track actively worked on code.

**Pull request closed without merging**
