### PR TITLE
USB-DFU: Detect flash page size from USB descriptor

### PR DESCRIPTION
**Pull request by tracernz**
Fixes the remaining item in #250. Can now support chips other than F303.

### CODE REVIEW

**Comment by tracernz** [comment]
I made a small improvement, taking the start addresses into account when calculating the available flash size. :)

**Comment by tracernz** [comment]
F4 complicates this a little. Just need to re-factor local erase and it will have full F4 support as well.

**Comment by tracernz** [comment]
Okay, this now supports F4 (and 99% sure it will support all STM32 chips) as well. Tested on Sparky1 and F4Discovery.

**Comment by hydra** [comment]
cool, I'll give this a whirl.

**Pull request merged**
