### PR TITLE
Add files for direct NW.js support

### PR DESCRIPTION
**Pull request by ambrosechua**
I propose this as a intermediary solution to #420 before deciding to rewrite the codebase. This instantly enables Cleanflight Configurator to be packaged as a native app. 

What is needed after this commit is a build process and a update notification/automation mechanism.

### CODE REVIEW

**Comment by ambrosechua** [comment]
I have some test builds [here](http://ambrose.makerforce.io/cleanflight/configurator-test-builds/) too.

**Comment by hydra** [comment]
very interesting, i will have to give this a try.  nice to see not many changes were needed to add support.   does it actually work?

**Comment by ambrosechua** [comment]
yes, me and @theepicflyer tested the windows and osx builds

**Comment by theepicflyer** [comment]
Everything works as far as I can tell, including reading sensors, writing configuration and firmware flashing. Only backup has an issue where the backup file is named differently from before, and errors as an incompatible version.

**Pull request closed without merging**
