### PR TITLE
Icon suggestions in scalable format (SVG) and bitmapped 128x128 (PNG)

### PR DESCRIPTION
**Pull request by Dvogonen**
My entries in the competition for new CleanFlight icon. Files available in scalable SVG format as well as in the same format as the current icon (128 pixels with a transparent frame around the icon). Comments about improvements are welcome. Especially as to the exact color hue etc.

### CODE REVIEW

**Comment by hydra** [comment]
problems?

**Comment by Dvogonen** [comment]
No, no problems. But I got no response at all on the pull request. Normally that means that there is no interest in the suggestion , so I revoked it.

**Comment by hydra** [comment]
I had looked at the images and was going to give you some feedback and when I was about to I noticed the PR’s had been closed :(

I like the CF logos, this one in particular:

https://github.com/Dvogonen/cleanflight-configurator/blob/c65b7cfa83abbab67097ad3fbb62654c11ae5b7a/images/icon2_128.png

Was wondering of the tails of the C and F could have gaps in them `||| || |`

I still like the current logo since it has a easily recognisable multirotor on it, i also like the 3D aspect of it.

Perhaps if you combined this one:

https://github.com/Dvogonen/cleanflight-configurator/blob/c65b7cfa83abbab67097ad3fbb62654c11ae5b7a/images/icon4_128.png

... and the first one i mentioned together, maybe get rid of the dark green background, and make the multi-rotor 3D?

What do you think?

**Comment by Dvogonen** [comment]
I'll give it a try tomorrow evening. 
I am not exactly clear over where you want gaps. In between the F and the c-like tail?  Or perhaps as an elongation of the vertical line behind the F all the way down so that it cuts through both of the circles?

**Comment by hydra** [comment]
Where the tail of the F turns anti clockwise into the C, I was thinking of putting the gaps in there to indicate motion and to give the F a bit more shape since its currently a cross between a j and an F.

**Comment by Dvogonen** [comment]
Take a look on the icons and tell my what you think.Besides implementing your suggestions I made a slightly updated icon variant that has the gap between the c and f and a more closed form. I think the result looks rather good.

**Comment by hydra** [comment]
Thanks for your entry @dvogonen much appreciated

**Pull request closed without merging**
