### PR TITLE
LEDstrip: Battery, Larson scanner, Blink on landing

### PR DESCRIPTION
**Pull request by gaelj**
Handle new MSP LED config format (not yet merged)
New function: Battery
RSSI is now a function (similar to battery, with blinking on low)
Blink is now an overlay
New overlays: Larson scanner, blink on landing
New overlay mixing possibilities

Requires the CF build resulting from https://github.com/cleanflight/cleanflight/pull/2160
Compatible with previous versions

NOT TO BE MERGED until https://github.com/cleanflight/cleanflight/pull/2160 is finalized.

### CODE REVIEW

**Comment by gaelj** [comment]
@skaman82 here is the PR you were expecting.
I'd be glad if you could test it extensively with CF 12, 13 & the new release.
@hydra and @ledvinap you might be interested too.

**Comment by skaman82** [comment]
Done extensive testing today. Everything is working fine. @hydra this can be merged with https://github.com/cleanflight/cleanflight/pull/2160

**Comment by gaelj** [comment]
The cleanflight code now doesn't require full chip erase.

**Comment by gaelj** [comment]
@skaman82 @hydra could you consider merging this as well as the LED strip ?
It's now part of Betaflight.

**Pull request merged**
