### PR TITLE
Serial: Attempt recovery of break condition

### PR DESCRIPTION
**Pull request by tracernz**
This attempts to recover after a break condition (occurs during reboot on older firmware versions). Tested and confirmed to work on Windows 10.

### CODE REVIEW

**Comment by tracernz** [comment]
Tested with Cleanflight 1.8.0.

**Comment by hydra** [comment]
Have you tried with with VCP targets too?

**Comment by tracernz** [comment]
They won't generate a break condition unless you explicitly generate one in the firmware as the serial interface is purely software. During reboot they will instead generate a device lost error or system error.

**Comment by hydra** [comment]
@tracernz Yup, this seems to work fine with old versions of firmware.  I also applied the same recovery and logging procedure to 'overrun' conditions which I had been receiving sometimes when connecting to some FC's here.

**Comment by tracernz** [comment]
@hydra, great, should alleviate some user frustration.

**Pull request merged**
