### PR TITLE
Configurator GUI rework phase 1

### PR DESCRIPTION
**Pull request by skaman82**
bildschirmfoto 2015-11-08 um 21 27 43

New try…

Don't merge now. Still have to do lot of work in the next weeks. Just announcing. Some help with JS would be very appreciated.

### CODE REVIEW

**Comment by fatcatfpv** [comment]
Let me know if my JS skills are neede, I can help whenever I have time. What do you need help with ?

**Comment by skaman82** [comment]
@fatcatfpv Thanks! Help is always welcome! Just have a look at the issue list here and pick something labeled "help wanted" or especially "important". :) https://github.com/skaman82/cleanflight-configurator/issues

**Comment by hydra** [comment]
well done regarding the git rebase.  You'll be a pro in no-time :smile: 

Yes adding the watermark on the CLI would be good.

Yes the icons/only collabsible size panel is an elegant solution. +1

Thanks for the HTML formatting, not looked yet but I'm sure any future merged should be easier now.

Yes, pulling in the changes for the PID tab seems good (with regards to all/useful pids).

Keep at it.  I would like to merge this soon, since there are so many changes this PR needs to be finished and included before anything else.

Please can you get this to a state where you think is is the MINIMUM you can do, then we can merge it, then we can add/improve other things in more PR's.  The sooner we merge the easier it will be for anyone else trying to work on the codebase.

**Comment by skaman82** [comment]
@hydra give me 4-6 days to wrap things up. I try to remove all unfinished code - then it will be easier to merge. There a tough thing to solve yet: the fixed bar that includes the save button on each tab doesn't work yet as planed. This is critical for usability but I can't solve this. Issue: https://github.com/skaman82/cleanflight-configurator/issues/7

**Comment by hydra** [comment]
I note that the 'documentation' link goes to the wrong place.

It should go to the documentation for the version of cleanflight the user is running, right now it seems to just go to the 'releases' page which is incorrect.

example url for v1.10.0:

```https://github.com/cleanflight/cleanflight/tree/v1.10.0/docs```

**Comment by skaman82** [comment]
@hydra already noted: https://github.com/skaman82/cleanflight-configurator/issues/6

**Comment by skaman82** [comment]
@hydra I am through with the rework phase and you can merge now if you like! Not yet fully satisfied with some details but the basic things are done now. Will now focusing on adding new features like profile switch and data flash bar in the header.

**Comment by skaman82** [comment]
This is the final status of my rework: 
bildschirmfoto 2015-11-08 um 21 27 33
bildschirmfoto 2015-11-08 um 21 27 36
bildschirmfoto 2015-11-08 um 21 27 39
bildschirmfoto 2015-11-08 um 21 27 43
bildschirmfoto 2015-11-08 um 21 27 46
bildschirmfoto 2015-11-08 um 21 27 49
bildschirmfoto 2015-11-08 um 21 27 52
bildschirmfoto 2015-11-08 um 21 27 55
bildschirmfoto 2015-11-08 um 21 27 59
bildschirmfoto 2015-11-08 um 21 28 02
bildschirmfoto 2015-11-08 um 21 28 05
bildschirmfoto 2015-11-08 um 21 28 08
bildschirmfoto 2015-11-08 um 21 28 10
bildschirmfoto 2015-11-08 um 21 28 15
bildschirmfoto 2015-11-08 um 21 28 30
bildschirmfoto 2015-11-08 um 21 29 28
bildschirmfoto 2015-11-08 um 21 29 30
bildschirmfoto 2015-11-08 um 21 29 33

**Comment by skaman82** [comment]
@hydra BTW didn't touched the LED Strip tab – just made it compatible with new window size and added common UI elements. Tooltips: I left two sample tooltips in the Config and PID tab.

**Comment by skaman82** [comment]
@hydra fixed some tiny issues. Now this PR is ready!

**Comment by hydra** [comment]
ready for review/merge?

**Comment by skaman82** [comment]
@hydra yes it is ready. there is a small issue in the sponsors tab in a certain situation but we can patch this after the merge!

**Comment by hydra** [comment]
ok, reviewing to merge now.  just had a play around with it. looking very nice!  great work!

**Comment by skaman82** [comment]
thanks. if you have some questions about my changes, I'm online for the next couple of hours

**Comment by hydra** [comment]
@skaman82 small bug with servo position indicators (probably motor ones too) when the value is 2000 it goes rom dark green (at 1999) to grey (at 2000).
The values for the motors/servos can go lower than 1000 and higher than 2000 depending on configurator.

**Comment by hydra** [comment]
As noted in IRC the tooltips content needs to be in messages.json.  Another PR is needed to fix that.

**Comment by hydra** [comment]
As noted, need a new PR to update the motor models.  One of the colors for the circles is: `#54AD1D` (taken from the updated quad_x_new.png file before it was deleted).

**Comment by hydra** [comment]
Merged!

Thanks for all your hard work so far.  I made a PR for your branch so you can easily review the additional changes I had to make to polish it up and fix failed merged.  Review each commit carefully so you can see what to avoid in the future.

I did some reformatting of the CSS and HTML - I'd had enough of all the space/tab/indentation issues from all the various authors in the past and figured now was a good time to apply some formatting.  

Maybe the formatting introduced errors,  definately worth testing presentation and behavior.

Feel free to give me a PR for the toggle switch size on the ports tab too.

**Comment by henn1001** [comment]
Looks fantastic guys! cheers

**Comment by tricopterY** [comment]
Great work - well done. And best of all @hydra is fully on-board :smile:

**Comment by borisbstyle** [comment]
Great job!

@hydra 
I would only bump configurator version to 1.00 instead of 0.67 as this is a major change to the gui

**Comment by skaman82** [comment]
@borisbstyle Tank you! There are some things to fix after the merge. Still work in progress.... but we are getting there :)

**Comment by skaman82** [comment]
@hydra as discussed a new PR with some bugfixes is ready. When it gets merged I move on to work on additional functionality in the header as planed. See https://github.com/cleanflight/cleanflight-configurator/pull/268

**Pull request merged**
