### PR TITLE
Serial: Buffer data received from serial

### LINKED ISSUE #254: CLI stalls when accessed via VCP port
I have observed that accessing cleanflight CLI on on an F1 board using MSP on VCP it seems to stall and stutter when doing larger transfers - like running 'dump'.  I also noticed the port utilisation value flash up a high value before returning to 0. Too fast to read the actual 

value from the screen update.

The same board when accessing CLI over USART1 works flawlessly.
The same board when accessing CLI from terminal emulator (putty) works flawlessly.

So seems to be something to do with the way that the configurator is managing the serial port and/or some interaction between USB VCP drivers and chrome.  

I I have seen the same thing on multiple development boards as well as a virgin CC3D board , so doesn't look to be hardware specific. 

Anyone got any ideas what it might be / where to look.

Long term I don't think i'm going to use VCP on my custom boards, but throw in a CH340G on usart1 instead to simplify reflashing anyway - but maybe beneficial for CC3D users if fixed.

### PR DESCRIPTION
**Pull request by tracernz**
Helps performance greatly when using VCP which returns data in 1 or 2 byte chunks at high rates. Fixes #254.

Data is buffered until either 20 bytes accumulates or no data is received in the last 5 ms. These thresholds are totally arbitrary so it may be worthwhile to attempt to tune them in some way.

P.S. @hydra You should change the default branch to development to avoid getting PRs against master, I almost did it here.

### CODE REVIEW

**Comment by ProDrone** [comment]
Is this a solution for the same problem addressed by the firmware pull requests:
https://github.com/cleanflight/cleanflight/pull/886,
https://github.com/cleanflight/cleanflight/pull/1143,
https://github.com/cleanflight/cleanflight/pull/1151

or should they both be merged for an even better result?

**Comment by tracernz** [comment]
Probably better to do it on firmware side if possible but doesn't look like things are moving there... I don't monitor the firmware repo so not up-to-date with it. ;-)

**Comment by hydra** [comment]
I have had the PR's prodrone mentions merged for a while here in a local branch with no adverse affects.  They will be merged soon, things are moving there @tracernz. :smile: 

This PR is still valid right now, but will probably be invalidated when the PR's @ProDrone mentions are merged.  We'll leave it open for now.

**Comment by tracernz** [comment]
Yep, sounds good.

**Pull request closed without merging**
