### PR TITLE
Yaw Expo in RC Tab

### PR DESCRIPTION
**Pull request by borisbstyle**
Guys who can help me out. I am running out of time, but it would be nice if someone can continue with it.

I am struggling finding a right tool to work with javascripts etc. At the moment I did it with my text editor.
At the moment the right value is not being read.

This is the new feature from 1.9.0 where there is yaw expo added.
https://github.com/cleanflight/cleanflight/pull/848

### CODE REVIEW

**Comment by hydra** [comment]
don't forget to make sure that backups saved with old configurator work with new code, new configurator must also still work with old firmware.  see also backup_restore.js

you might need also to bump the api version in cleanflight to 1.10, see serial_msp.c

**Comment by hydra** [comment]
also the ui should hide the yaw expo field if the firmware does not support it, there are other examples of this behaviour on the pid tuning tab.

**Comment by borisbstyle** [comment]
Yes I will test that and indeed try to make sure that the field will be hidden when there is older version detected.
Just need some time to understand the code a bit better how the MSP stuff works in here.

**Comment by borisbstyle** [comment]
Hey @hydra. I think there is a bug in api version detection? The version now is 1.10, but still being detected as not greater or equal to 1.2? Api version 1.9 was considered as fine, but 10 not being accepted.

Accepted version in current code (backup_restore.js):
'apiVersionAccepted': 1.2,

Check for acception (serial_backend.js)
if (CONFIG.apiVersion >= CONFIGURATOR.apiVersionAccepted) {

**Comment by borisbstyle** [comment]
I think it thints 1.10 is greater than 1.2, which actually is the case.

Can someone else/you fix the bug on all places as this version comparisation is everywhere through the code.
Other option would be to bump api to 2.0? What do you think?

**Comment by borisbstyle** [comment]
@hydra Could it be that I am facing these issues due to 2 byte throttlepid attenuation value before yaw_expo? I am getting wrong values for yaw expo in the gui and can't figure out why.
We used datasize 11, but it should perhaps be 12?

currentControlRateProfile->tpa_breakpoint = read16(); <<<<<2 bytes?
if (currentPort->dataSize >= 11) {
                currentControlRateProfile->rcYawExpo8 = read8();
            }

**Comment by tricopterY** [comment]
@borisbstyle 
```C
case MSP_RC_TUNING:
         headSerialReply(10);
         serialize8(currentControlRateProfile->rcRate8);
         serialize8(currentControlRateProfile->rcExpo8);
         for (i = 0 ; i < 3; i++) {
             serialize8(currentControlRateProfile->rates[i]); // R,P,Y see flight_dynamics_index_t
         }
         serialize8(currentControlRateProfile->dynThrPID);
         serialize8(currentControlRateProfile->thrMid8);
         serialize8(currentControlRateProfile->thrExpo8);
        serialize8(currentControlRateProfile->rcYawExpo8);
         serialize16(currentControlRateProfile->tpa_breakpoint);
         break;
```
You must change to
headSerialReply(11);

**Comment by borisbstyle** [comment]
Well that was in the last master right? That's what I was testing. It worked in the beginning. But I have must screwed up something down the road.
Will redownload latest master and check again.

**Comment by tricopterY** [comment]
@borisbstyle - You may have been using cleanflight/cleanflight/issues/848

**Comment by borisbstyle** [comment]
Hydra changed that in another commit from him

**Comment by tricopterY** [comment]
:smile: - cool

**Comment by hydra** [comment]
ok, development configurator updated to work with apiVersion >= 0.10.0 using semver library.  See commit 244685c9a69f5a2baa2531ccddfe4d463c64f2ab on development branch.

**Comment by borisbstyle** [comment]
This is what I get when using current master and the latest configurator

2015-05-07 @ 23:55:01 -- MultiWii API version received - 1.10
2015-05-07 @ 23:55:01 -- This firmware version is not supported. Please upgrade to firmware that supports api version 1.2 or higher. Use CLI for backup before flashing. CLI backup/restore procedure is in the documention.

**Comment by borisbstyle** [comment]
What's the best approach for me now? Resync my full version with the one from your version fix?

**Comment by borisbstyle** [comment]
I will remove this P/R and start all over again on the development version

**Comment by tricopterY** [comment]
@hydra - https://github.com/cleanflight/cleanflight-configurator/commit/244685c9a69f5a2baa2531ccddfe4d463c64f2ab
just killed all of my efforts in PR cleanflight/cleanflight-configurator#176.
Should I redo them using semver, so you can merge, or delete the PR altogether.

**Pull request closed without merging**
