### PR TITLE
Added 3D configuration parameters so they don't have to be changed in…

### PR DESCRIPTION
**Pull request by NightHawk32**
… the CLI.
These parameters now are in the configuration tab, bottom left. 
My other pull request implements the new MSP IDs in the cleanflight firmware.
I added these parameters to the MSP to have them for the motor test. At the moment deactivating motor test sets the throttle value to 1000 which causes 3D ESC to run at full neagtive throttle. Now I can query the neutral value for 3D mode and deactivate the motors properly if the 3D mode is set.
I will fix this problem next.

### CODE REVIEW

**Comment by NightHawk32** [comment]
I did some testing with a new Copter, now it is safe to use the motor-test feature without any danger in 3D mode.

**Comment by hydra** [comment]
this pr targets the wrong branch (`master`).  going to merge to `development`.

**Comment by hydra** [comment]
merged to `development`

**Comment by hydra** [comment]
You missed the following

* missing backup and restore functionalty
* missing configuration migration logic
* missing visibility toggling of 3D section when API version < `1.14.0`
* missing logic for issuing the correct sequence of MSP commands issues when API version < `1.14.0` when viewing the configuration tab.

Please see ec57aa9d1afcb37d30d818e63fd12d409ab53a56

Please test latest code against backups made with earlier version.
Please test latest code against Cleanflight 1.10.0 (or earlier) and Cleanflight 1.11.0 (latest master)

**Comment by NightHawk32** [comment]
Ok thanks for the feedback, I'm just trying to get into this project, I will have a close look at at your commit, so I can analyze, what I forgot.

**Comment by hydra** [comment]
no worries, thanks for the commits to both the configurator and the firmware.  Nice to have another dev that understands both environments.

**Comment by hydra** [comment]
also, if you have any additional tips on how to configure for 3D flight the manual could likely do with an update in that area.

**Comment by skaman82** [comment]
@NightHawk32 I'm not sure, but I think your changes messed up the motors tab. The motor test mode is now on on default.

**Comment by skaman82** [comment]
@NightHawk32 sorry, that was not your code. I just found out that the motors tab behaves this way also in earlier versions. Just never activated the 3D feature before. :)

**Pull request closed without merging**
