### PR TITLE
Support for next lap timer

### PR DESCRIPTION
**Pull request by error414**
Hi,

I did changes what you wanted.

reference to https://github.com/cleanflight/cleanflight-configurator/pull/445

### CODE REVIEW

**Comment by hydra** [comment]
hi, i gave this a test today and it look OK however there's one thing that needs fixing:

when you change the drop-down from ilap to aritimer, and then change it back to ilap (without pressing save) the iLap transponder code is lost.

suggest maintaining internal state for each transponder provider and using it as appropriate.

please also rebase again and fix the code-style issues
* use space characters ` `  between `if` and `(` i.e. `if (` not `if(`
* use space characters ` `  around `else` i.e. `} else {` not `}else{`
* use space character after parameter lists, e.g. `function(provider) {`  not `function(provider){`

also remove the old commented out html block in the transponder.html file.

I should also note that we now have three ways in the codebase of building elements.

1) using strings (blurgh)
2) using templates (see power.js and power.html)
3) and using jQuery DOM building (as seen in this PR).

I'm OK with that but perhaps would have preferred a bit more consistency with the rest of the codebase.

**Comment by error414** [comment]
Hi,

I did changes what you want. I think that would be nicer to use real JS template system like https://github.com/BorisMoore/jsrender. For jquery exists unlimited template systems.

**Comment by hydra** [comment]
@error414 yes, there has been a lot of talk about reworking the GUI, it needs a JS expert to take ownership of the task and manage it.  No-one has stepped forwards yet.   We need a system that other developers would want to work on, angularjs and react js are likely candidates.

**Comment by hydra** [comment]
great, merged. thanks for doing the requested updates, much appreciated.

**Pull request merged**
