### PR TITLE
Pid Tab rework

### PR DESCRIPTION
**Pull request by VirtualEnder**
Reworked the PID page so only the PIDs for detected hardware show up.  Also refactored the code that handled the naming of the rows for PID values to not be dependent on order.  Now matches the row class to the PID_names value.

### CODE REVIEW

**Comment by thenickdude** [comment]
Here's a screenshot of your redesign for reference:

screen shot 2015-09-06 at 9 19 11 pm

It seems like this will help out a lot with making it clear what each PID is for (so people don't futilely try to change PIDs which don't affect their craft).

However, it doesn't really work for GPS/navigation. This is because despite GPS being enabled and assigned to a serial port, the FC only reports the GPS sensor as being present if the GPS receiver has achieved a 5 satellite lock. So most of the time people won't be able to edit their navigation PIDs.

**Comment by VirtualEnder** [comment]
Awesome! Thanks, I don't have the GPS to test with, so your testing is perfect! I'll look for an alternative way to detect the GPS.

**Comment by thenickdude** [comment]
You can probably copy configuration.js's read of the FEATURE_GPS bit (bit 7) in `BF_CONFIG.features`, loaded by the MSP_BF_CONFIG message.

**Comment by VirtualEnder** [comment]
Also, I think I'm going to add a "show all" button to override the auto detection.

**Comment by thenickdude** [comment]
Yeah, that's a great idea!

**Comment by VirtualEnder** [comment]
Doing some research on this.  I got it working, but the source of cleanflight seems to suggest that MSP_BF_CONFIG is depreciated.  Looking for a newer method of determining settings. BF_CONFIG would have been nice, because it looks like I could read it all directly instead of relying on the "on" lights to determine features, which was fast, but hackish.

**Comment by VirtualEnder** [comment]
I just used BF_CONFIG for now, but will need to be changed at some point.  Also reworked the code to detect the sensors directly instead of relying on the "ON" lights, which was kind of hackish and not ideal.

**Comment by hydra** [comment]
@VirtualEnder Thanks for the work so far, we'll get this included i a forthcoming release.

**Comment by VirtualEnder** [comment]
Thanks, let me know if it needs refactoring at any point or if there are any suggestions for code changes.

**Comment by hydra** [comment]
See #266 - it's being merged into that.

**Comment by hydra** [comment]
this is merged.  Please test and review `development` branch.

**Pull request closed without merging**
