### PR TITLE
Enable flashing using USB-DFU protocol

### LINKED ISSUE #65: Flashing - Support STM32F3 based targets in DFU mode.
Looks to be the code already contain parts to enable DFU flashing? Not sure what the actual state is and if this part of the code is already working. Actually the GUI is only allowing Hex files to be selected and will do some basic tests. Also an STM device in boot mode is not detected by the GUI. Would be nice to be able to flash all targets easily via the GUI.

I have opened an related issue in CF already:
https://github.com/cleanflight/cleanflight/issues/412

### PR DESCRIPTION
**Pull request by tracernz**
For new boards like Tornado.
Fixes #65 .

Todo:
- [x] Auto-detect DFU mode after reboot
- [x] Implement local flash erase
- [ ] Detect chip ID/ flash page size for local erase
- [x] Make USB permissions compulsory
- [x] Add more error checking

### CODE REVIEW

**Comment by tracernz** [comment]
This is the minimal changes to get DFU support. The problem is that the reboot sequence reboots the board but then tries to connect via serial (and the USB-CDC serial device disappears when the board boots in DFU mode). There isn't an obvious/simple solution to detect whether to reconnect with the serial or DFU driver as the firmware flasher has no idea what type of board is connected. Perhaps the user will need to select (e.g. using a checkbox) to use DFU mode?

**Comment by tracernz** [comment]
Okay, I've pushed a commit which waits a short time after the reboot, and then checks if a DFU device is detected. It works successfully on my F3 Disco (DFU mode), and a Naze32 (serial).

**Comment by sambas** [comment]
works nicely on windows 10 and colibri_race target
https://www.dropbox.com/s/oe74ss9qq6dm86r/Screenshot%202015-10-03%2011.45.08.png?dl=0
https://www.dropbox.com/s/o5q9vmorkdykduc/Screenshot%202015-10-03%2011.45.10.png?dl=0

**Comment by tracernz** [comment]
In the DFU code there was a call to a function cleaned up in c038785 still left behind. This was causing an exception to be thrown (invisible to the user as it didn't break anything). I have removed the offending call.

**Comment by MJ666** [comment]
I have tested with an AlienWii F3 board and the board goes to DFU mode (verified with DFUSeDemo)but the DFU device is not detected by the configurator and flashing does not work. I tried the the Sparky and the AlienWiiF3 firmware. Anything special with the flashing procedure?

**Comment by tracernz** [comment]
@MJ666 Any chance you could copy and paste the javascript console output? Which OS? The configurator doesn't show a device called DFU in the connection dropdown even after a little time?

**Comment by MJ666** [comment]
I'm running Windows 10. Never have used the Java console before? I did some testing a couple of months ago with uncommenting the USB part in the configurator code. This time the DFU device showed up. But this was with Windows 8.1. The stm driver is properly installed since DFUSeDemo is working. I will travel now for a while an time at home is limited. If you have some short test I can try again.

**Comment by tracernz** [comment]
Unfortunately my time is also very limited at the moment. I'll get back to you in a couple of days when I'm freed up a little. :)

**Comment by tracernz** [comment]
@MJ666, I wonder if you didn't notice the optional permissions box?
screen
I'm thinking about just adding the USB permissions to the normal list accepted upon app installation (i.e. like serial, filesystem, etc.) to avoid this, but the code was already written so I kept it for now. Thoughts?

**Comment by MJ666** [comment]
I have seen and enabled this. Found this alredy in my experiments. Don't see a problem how this works for now. It's likely more easy if this is enabled by default.

**Comment by tracernz** [comment]
@MJ666, can you try again please? I have made the DFU device check after reboot more robust.

USB permissions are now compulsory as discussed with @hydra.

**Comment by tracernz** [comment]
I've added support for local erase (to avoid erasing configuration). The problem with this is that I could not find a way to figure out the page size of the device so at this stage a page size of 2 kB is hardcoded for the STM32F303. There is no DFU command to retrieve device identifying information, these are some of the methods I've looked at:
* Reading flash size, problem: this is at 0x1FFF7A22 on F303 but different locations on F405 etc. May actually be be a good unofficial way to identify but I haven't looked into it further yet.
* Dumping entire bootloader ROM and searching for identifier
* Dumping bootloader SRAM and searching for identifier
* Chrome USB descriptors, problem: on Linux at least, Chrome doesn't provide the interface descriptor string which has the page size and flash size information (e.g. `iInterface              4 @Internal Flash  /0x08000000/128*0002Kg`). May be able to get this by handcrafting some USB control transfers but difficult, I might look into this later.
* Writing a very minimal STM32 program which reads the chip ID, puts it into an accessible memory location and jumps to the bootloader, this could then be flashed by configurator, booted and then read the chip ID, and continue with normal firmware flashing. Last resort I think.

It will work fine with the hardcoded page size while only F303 devices are supported but I don't want to leave a grenade like that for somebody else when new devices are brought up.

**Comment by MJ666** [comment]
Will try if I'm back home. Unfortunately this may take a while. Will be traveling a lot and will be at home for always a few hours only in the next weeks.

**Comment by tracernz** [comment]
@MJ666 There is a problem on Windows with the OS claiming the device and making it unavailable to Chrome apps (Chrome doesn't allow already claimed devices to be released for security reasons sadly). 

The solution is to replace the ST driver with a libusb driver. The easiest way to do that is to download [Zadig](http://zadig.akeo.ie/). 
With the board connected and in bootloader mode (reset it by sending the character R via serial, or simply attempt to flash it with the correct serial port selected in Configurator): 
* Open Zadig
* Choose Options > List All Devices
* Select `STM32 BOOTLOADER` in the device list
* Choose `WinUSB (v6.x.x.x)` in the right hand box
windows 10
* Click Replace Driver
* Restart Chrome (make sure it is completely closed, logout and login if unsure)
* Now the DFU device should be seen by Configurator

**Comment by tracernz** [comment]
I've put together some rough notes on this: https://github.com/tracernz/cleanflight/blob/usb-flashing-docs/docs/USB%20Flashing.md

**Comment by MJ666** [comment]
Make a short test and have flashed the AlienWii32 F3 successfully. Very nice. Many Thanks.

**Comment by tracernz** [comment]
@MJ666 Just to confirm, did you need to install alternate driver using Zadig? Thanks very much for testing. :)

**Comment by MJ666** [comment]
Yes, I used the Zadig driver as you described.

**Comment by tracernz** [comment]
@MJ666 Thanks for confirming. I had the same problem on a virtual machine. Good luck with your work. :)

**Comment by hydra** [comment]
@tracernz Keep up the great work!

**Comment by hydra** [comment]
Aside from the flash size issue, is there anything else left to do? (other than testing and potential cleanups).

I'm thinking we should merge this and then later add support for different flash sizes as needed.

**Comment by hydra** [comment]
Also, can you rebase too please.

**Comment by tracernz** [comment]
@hydra Yeah, just the page size left to do at this stage. I'm happy for this to merge as-is now because we only have F303 targets with DFU at this point. I'll raise an issue to continue work on the chip ID/page size detection when you merge.

P.S. Rebased to development branch head.

**Comment by hydra** [comment]
@tracernz great.

I asked the guys from TBS to test it this morning and they ran into some issues, hopefully trappy / @larryho5 will update this with their findings.

**Comment by tbs-trappy** [comment]
@hydra yeah we got some issues with the board not getting recognized. I ran zadig and went through the whole lot of USB drivers available, nothing made "DFU" appear from the drop-down list. It's a bit of good news because I was starting to doubt my coding skills when I tried to look into this some weeks ago and just couldn't get it working ;)

@tracernz if you need any help let me know. we're on a similar timezone and I can try a few things side-by-side with our hardware here to see if we can get it to work. the flasher tools from motomoto and dfuse works without issues, so it's got to be something in the code or in chrome.

**Comment by tbs-trappy** [comment]
@hydra @tracernz nevermind, turns out there was a chrome instance running in the background. force-closed it with task manager, re-launched configurator, now it works. found another issue, will report to @hydra :)

**Comment by tracernz** [comment]
@tbs-trappy Great to hear. :) Let me know if there are any further issues/tidy-ups for this. ;)

**Comment by hydra** [comment]
merging to development, we'll fix up as required.

**Comment by hydra** [comment]
Flashed my new board with it, worked great :smile:

**Pull request merged**
