### PR TITLE
replace MSP_BF_CONFIG and MSP_SET_BF_CONFIG which more specific commands

### PR DESCRIPTION
**Pull request by frog32**
This doesn't include backup functionality. Backup functionality should be changed at a later stage.

### CODE REVIEW

**Comment by hydra** [comment]
I added current_meter_type in 7bd98e557a8eac7b74d55d6da31876ea83b6c059

**Comment by hydra** [comment]
There is a bit more work to do here.  The backup_restore.js needs updating too, do a project wide search for BF_CONFIG in the *.js files and you'll find it.

**Comment by hydra** [comment]
@frog32 any update?

**Comment by frog32** [comment]
i am still working on this one. since backup_restore.js is also affected by other changes i am doing right now, il'll probably combine the changes. this pr is not superurgent because the BF_CONFIG should do the job just fine for an other week.

**Comment by hydra** [comment]
@frog32 Any update?

**Comment by hydra** [comment]
@frog32 Did you forget about this PR?  Would like this completed if you have time?

**Comment by hydra** [comment]
closing this for now, code is out of date.

**Pull request closed without merging**
