### PR TITLE
Added support for Selective Software Filtering (and yaw P limit) in GUI

### PR DESCRIPTION
**Pull request by ProDrone**
Support for PR https://github.com/cleanflight/cleanflight/pull/1028
Requires the MSP commands from this PR: https://github.com/cleanflight/cleanflight/pull/1081

### CODE REVIEW

**Comment by borisbstyle** [comment]
You should add yaw_jump_prevention_limit as well if you added the yaw p limit in there.

**Comment by ProDrone** [comment]
Thanks @borisbstyle. Already __done__ :grinning:, here and in the complementing https://github.com/cleanflight/cleanflight/pull/1081

**Comment by hydra** [comment]
Will merge f8bfb33 and 25bd4a8.  That's good.  Could you move them to a new PR by themselves?

The rest is blocked until we answer questions regarding some firmware code.

**Comment by ProDrone** [comment]
@hydra  Separate pull request made for the above mentioned https://github.com/cleanflight/cleanflight-configurator/commit/f8bfb332f3bdaabd5a04f2bcf76044c4b1a76b49 and https://github.com/cleanflight/cleanflight-configurator/commit/25bd4a825388d96e7fea11f0b69be5c65d8e0351 in https://github.com/cleanflight/cleanflight-configurator/pull/220

**Pull request closed without merging**
