### PR TITLE
New orientation images

### PR DESCRIPTION
**Pull request by Dvogonen**
I read that the motor orientation images need to be replaced  in cleanflight-configurator. I have prepared new SVG images that should be drop in replacements for the originals.
I am very doubtfull if the tricopter image is correct, since all motors are rotating in the same direction. But that is the way the original is drawn, so thats how i did the new image.

### CODE REVIEW

**Comment by thenickdude** [comment]
Actually that's correct for tricopters, some people run them like that so they only need to buy one kind of prop. The controller doesn't care what direction the motors spin because it uses tail tilt for yaw instead of motor torque.

**Comment by Dvogonen** [comment]
True. The flight controller can compensate the torque effect cause by having all motors spinning in the same direction. But I have always thought that the normal way of setting up a tricopter is to let the two front props counter rotate to avoid as much of the torque effect as possible. The image gives the impression that it is the other way around.

**Comment by hydra** [comment]
Hi @Dvogonen thanks for these.

I've just merged in new images from stronnag - into the development branch, perhaps prematurely in light of this, but can revert them without issue.  I will check with the compo moderators to see which ones people like best and we'll go from there.  The ones stronnag did are generated using a script which means they are easy to change programmatically which is nice.   Did you use a script to generate your ones?

**Comment by Dvogonen** [comment]
The images were created in inkscape, not scripted. They are however quite easy to change. Probably the only good aspect of the substandard SVG image format.

**Comment by Dvogonen** [comment]
I checked the SVG source code in the pull request and found a few problems. Both these files and the files you just added in the development branch contain faulty copyright notices that basically says that the files can only be used in Baseflight configurator.
I also spotted that i forgot to remove a gray square from the file atail_quad.svg. I used the square to look for white on white objects.

**Comment by hydra** [comment]
The svgs in the dev branch look ok, the /old/ files contain the old copyright messages (in red) - i was looking here:

https://github.com/cleanflight/cleanflight-configurator/pull/49/files

where were you looking?

you can add another commit to your pull request that fixes the image.

**Comment by Dvogonen** [comment]
There is one branch called development and another called baseflight-configurator-development. I must have looked in the wrong one. I have never done a commit to a pull request before. Interesting exercise.

**Comment by Dvogonen** [comment]
That was easy...

**Pull request closed without merging**
