### PR TITLE
GUI rework phase 2: New Features

### PR DESCRIPTION
**Pull request by skaman82**
@hydra some new stuff is ready for the configurator! 

New features:
New global profile selector in the header (removed it from the PID tab)
New global dataflash status bar in the header
New map functionality in the GPS tab showing current position (internet connection required)
Preferred log position (opened/closed) is being saved now for the next launch of the configurator
Further rework of the documentation tab

Bugfixes and adjustments:
Higher resolution for the 3D model in the config tab (looked low-res on retina displays)
Small fixes in the log (shows now the last line when log closes)
Small css adjustment in the config tab (margin of the new 3D box)
Small responsive adjustments of the tab menu

bildschirmfoto 2015-12-02 um 22 44 26

Thanks @NightHawk32 for help!

### CODE REVIEW

**Comment by skaman82** [comment]
@hydra this one is still open. Will you merge this next?

**Comment by hydra** [comment]
Hiya, I've been busy moving house.  Looking at this now.

**Comment by hydra** [comment]
Please can you make more granular PR's please.  Each PR should add/delete/change one thing (or set of related things) at a time.  e.g. a PR to update the GPS tab, a PR to fix styling issues, etc.

Having one giant PR makes it much harder to:
a) review
b) discuss
c) test
d) merge

**Comment by skaman82** [comment]
Great! Have the next pr lined up already :) Will submit it in a fiew days. That one will also require a API bump like the failsafe tab.

Von meinem iPhone gesendet

**Comment by skaman82** [comment]
Ok, will do. The next PR is almost ready and contains also numerous small things. After that it will be one pr for each change/feature:)

Von meinem iPhone gesendet

**Comment by hydra** [comment]
@skaman82 thanks.

Please avoid changing any more dataflash code as there are a bunch of upcoming firmware and UI changes that have already been made but not merged yet.

**Comment by skaman82** [comment]
Thanks!

You said that the LED tab is getting a rework. Can you tell me who is working on it? Would like to help with the interface if I may.

**Pull request merged**
