### PR TITLE
Issue #74: Show battery & statuses in top bar

### PR DESCRIPTION
**Pull request by gaelj**
- Battery voltage appears as a horizontal bar
- Autodetection of battery type is used to calculate the bar min, max &
alarm values according to the battery configuration parameters.
- Color changes to red when battery level goes under the alarm setting
- Armed, failsafe and Serial Link status icons below battery voltage
monitor
- Change calibration button contents to "Calibrating" during calibration

### CODE REVIEW

**Comment by gaelj** [comment]
First draft:

capture d ecran 2016-04-20 01 52 35

**Comment by skaman82** [comment]
@gaelj Great job, I will post some litte css adjustments later to make it perfect :)

**Comment by skaman82** [comment]
@gaelj with this changes it should look nicer:

´´
.battery-icon {
    background-image: url(images/icons/cf_icon_bat_grey.svg);
    background-size: contain;
    background-position: center;
    display: inline-block;
    height: 30px;
    width: 60px;
    transition: none;
    margin-top: 4px;
    background-repeat: no-repeat;
    
    
.quad-status-contents {
    display: none;
    margin-top: 10px;
    margin-left: 14px;
    height: 10px;
    width: 30px;
    
.battery-status {
    height: 11px;
    position: relative;
    box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.20);
    border-radius: 0px;
    background-color: #59AA29;
    /* border-radius: 4px; */
    margin-top: 0px;

.quad-status-contents {
    display: none;
    margin-top: 10px;
    margin-left: 14px;
    height: 10px;
    width: 40px;
    
.bottomStatusIcons {
    background-color: #272727;
    height: 31px;
    margin-top: 2px;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;

**Comment by gaelj** [comment]
Done. I agree it's much better. Thanks !

**Comment by skaman82** [comment]
I have noticed a small CSS bug: in .quad-status-contents width: should be 30px. Otherwise the status bar is too long.

**Comment by skaman82** [comment]
Other CSS optimization: in .battery-legend set margin-left to -8px;

**Comment by skaman82** [comment]
@hydra this is nice. If you have no concerns about this I will merge this tonight and tune some css things a little.

**Comment by skaman82** [comment]
Merged. Cleanup follows shortly

**Comment by skaman82** [comment]
clean-up also merged

**Comment by gaelj** [comment]
Thanks !

**Pull request merged**
