### PR TITLE
OSD tab JS - first cut

### PR DESCRIPTION
**Pull request by gaelj**
Based on @nathantsoi's ongoing Betaflight implementation.

- parse & use cleanflight font file
- soft data source for OSD elements & video formats
- sliders sets OSD blocks visibility
- mouse drag moves OSD blocks
- no MSP implementation yet (waiting on @hydra's CF update or more details)
- no live data, only static examples

### CODE REVIEW

**Comment by gaelj** [comment]
@skaman82, let's have your feedback on this !

**Comment by skaman82** [comment]
@gaelj there some files missing (mcm font and two js libraries). After reading them I could test this.

It could be cool if you could highlight the selected element on the preview screen also in the OSD elements box on the left. (add active class to the elementselect DIV).

@hydra the font is not really ready. There are no icons or bars-charachters in it. When do you think you can update the font?
bildschirmfoto 2016-06-30 um 10 17 42

**Comment by gaelj** [comment]
@skaman82 fixed; along with other improvements.

**Comment by gaelj** [comment]
Highlighting of hovered osd block is ready.

**Comment by gaelj** [comment]
What else ? :)

**Comment by skaman82** [comment]
I fear we have to wait until we know exactly the elements there will be in the osd to configure. It would be great of course if we could support a editable callsign, multiple layout pages and a osd_switch setting (selects a page layout that will be enabled with the osd_switch mode)

**Comment by skaman82** [comment]
@hydra did you send @gaelj and me some hardware to play with?

**Comment by skaman82** [comment]
@gaelj really nice work so far! Just some VERY minor stuff:

- border radius of 3px would be nice on the hover backdrop.
- there is some strange padding at the bottom in the hover backdrop (but not on vtxCH group).
Just compare the bottom areas:

bildschirmfoto 2016-06-30 um 23 40 36
bildschirmfoto 2016-06-30 um 23 40 29

**Comment by skaman82** [comment]
please add the following line to:
`.tab-osd .osd_canvas
`

` 
background-size: 360px 234px;
`

then the canvas grid will be ok.

**Comment by hydra** [comment]
looking good.  I've been busy with hardware these last few weeks and should have more time to work on the OSD display elements soon now that the hardware is done.  My current hardware product (not the standalone OSD) has been very time consuming indeed.

**Comment by skaman82** [comment]
@gaelj merging this, thank you so far. The work continues when we have more details on what type of displayed elements there will be (artificial horizon, flight mode icons... and so on) and more font characters to get this done.

**Pull request merged**
