### PR TITLE
Enhancement to Configuration tab to cater for auto_disarm_delay and disarm_kill_switch

### PR DESCRIPTION
**Pull request by tricopterY**
cleanflight/cleanflight-configurator#77

### CODE REVIEW

**Comment by tricopterY** [comment]
My proposal for LOOP_TIME
x

**Comment by tricopterY** [comment]
My proposal for LOOP_TIME:
x

Spinner change updates Cycles per Second, save button at the bottom (not shown) would save new value.

**Comment by hydra** [comment]
Merged, please review 045d2b0ca462f3277df156e76b7a704bbf5f75a3.

**Comment by tricopterY** [comment]
@hydra - configurator tab is already cluttered. I thought the setup tab would be a better place for the FC loop time. Also, the back up button gives confidence that user is backing up the loop time too.
To me, loop time is a one-off set up function. Please advise, before I attempt a PR.

**Pull request merged**
