### PR TITLE
Translate to spanish lang

### PR DESCRIPTION
**Pull request by dorobon**
:)

### CODE REVIEW

**Comment by hydra** [comment]
me gusta! muchas gracias.  mi espanol es muy muy malo...

ok, back to english, yes my spanish is bad.  that's a lot of translation work, thanks for spending time working on it.

I'm happy to merge this but only if you are happy to maintain the spanish language translations.

I would recommend finding or making some kind of tool to help you manage translations.

there are some issues we need to solve.
1. when an english message is updated, how will you know know you need to translate it?
2. what happens when a spanish translation is missing?  does it currently fall-back to english or is there missing text?

**Comment by McGiverGim** [comment]
I can help translating into spanish if @dorobon has no time in a future or need some help. I'm experienced, I translate a lot of projects in my free time (specially Android apps).

I suggest use an external management system, in this way is easy to collaborate and we don't need to make a merge manually. Only download and commit from time to time the file. Some like:
- https://www.oneskyapp.com
- https://www.getlocalization.com/
- https://crowdin.com/
- ...
Some time ago all were free for GNU projects, but now it's a different thing. Maybe we can't start with OneSkyApp, that is free for little projects, and change to other it does not meet the requirements.

I suggest add a combo in the config of the app to let the people change the language (in this way, if some translations are bad quality, the user can fallback to english).

Regards!

**Comment by dorobon** [comment]
I`m happy to translate all the strings to spanish. when it is finished i will commit again.

> there are some issues we need to solve.
> 
> 1 when an english message is updated, how will you know know you need to translate it?
> 2 what happens when a spanish translation is missing? does it currently fall-back to english or is there missing text?

1 -> When i use CF, if i see an engligh text, i add to my specific lang file this new string
2 -> When a string is not found in a specific language, the english version will be showed.
 
OR find free a web tool for translate projects

**Comment by McGiverGim** [comment]
How goes this translation? 😊

I've added the translation to oneskyapp. It's not the best but it's free for open translations:

http://cleanflight.oneskyapp.com

I can add more languages if this works. What do you think?

**Comment by McGiverGim** [comment]
I close this. I've made another PR with the complete translation.

**Pull request closed without merging**
