### PR TITLE
LED Strip GUI: color, mode color setup

### PR DESCRIPTION
**Pull request by gaelj**
For discussion, this is a first shot at implementing LED Strip commands in GUI : 

- Color setup (HSV sliders) of the 16 colors in the palette (cli command color)
- Mode Colors and Special Colors setup: click on one of the buttons, then on a color in the palette (requires https://github.com/cleanflight/cleanflight/pull/2173)

Backup files also now include the LED color and mode color data.

### CODE REVIEW

**Comment by gaelj** [comment]
capture d ecran 2016-05-27 23 18 41

**Comment by skaman82** [comment]
@gaelj great work on this! This is a load of new buttons.... 
Maybe it would be nice to leave something out to not overload it.

I would leave out:
• HSV sliders > just use the color palette
• In special colors > Animation, Background and Blink background

Other thoughts: 
I guess this would not fit on a 8" tablet screen anymore - but have to test it.
Otherwise I would suggest trying to fit this in - even if the user has to scroll down more.

**Comment by gaelj** [comment]
- replace functions buttons by drop-down list (main led function) + switches (color modifiers / overlays)
- hide unused controls
- display color modifier / overlay flags on grid LEDs as colored dots in the corners
- use a drop-down list to chose mode color group, instead of displaying colors from all groups at once
- color editing sliders are in  a pop-up that shows when a color is clicked

capture d ecran 2016-05-30 01 48 41
capture d ecran 2016-05-30 01 49 01
capture d ecran 2016-05-30 01 49 11
capture d ecran 2016-05-30 01 49 26
capture d ecran 2016-05-30 01 49 30
capture d ecran 2016-05-30 01 49 34
capture d ecran 2016-05-30 01 49 37
capture d ecran 2016-05-30 01 57 09

**Comment by hydra** [comment]
ahh nice, I'll have to give it a whirl.

**Comment by gaelj** [comment]
I just solved a performance bug + added an overlay on each LED when in color mode, showing the actual LED's color.

Any suggestions ?


capture d ecran 2016-05-30 22 54 39

**Comment by skaman82** [comment]
@gaelj great idea! Ich will check this out soon

**Comment by gaelj** [comment]
Here is a hex that will let you take full advantage (SP Racing F3). It's up to date with latest main at this time + includes LED battery and MSP mode color code.
[cleanflight_SPRACINGF3.zip](https://github.com/cleanflight/cleanflight-configurator/files/290085/cleanflight_SPRACINGF3.zip)

**Comment by gaelj** [comment]
All commits squashed.
@skaman82, any feedback ?

**Comment by skaman82** [comment]
Still had not enought time to play with this. I'll try to give you my Feedback this weekend.

Von meinem iPhone gesendet

**Comment by hydra** [comment]
ok, 1.13.0 final is out so the new MSP commands are ready for use.

**Comment by skaman82** [comment]
Tested this today. Relly nice work @gaelj 

Found a small bug regarding special colors: When I want to change the color in the "special colors" section the color isn't applied on first click. It is only applied when I click on other special colors element or any other color. For example:

I want to change the armed color.
1. I apply "armed state" to a LED in the grid
2. I click on "Armed" button and click on a color I like (hsv mixer appears, but the color in the Armed button does not change)
3. The color in the "Armed" button only changes to the selected on if I click on another color or on the "disarmed" button.
The color change is applied to the connected led strip directly - it only don't updates in the GUI on the first klick.


bildschirmfoto 2016-06-12 um 15 03 23

**Comment by skaman82** [comment]
Second bug:
bildschirmfoto 2016-06-12 um 15 16 01

Sometimes the wiring order gets messed up after mode change.

1. Defined three LEDs (0-2)
2. Apply "armed state" to LED 1
3. Change special colors
4. Apply "GPS" to the same LED > The grid only shows two LEDs now (0 and 2)
After reloading the led tab the order is correct again.

**Comment by skaman82** [comment]
We have 16 colors to chose from so I don't think that the HSV mixer ist really necessary. It only complicates the apply process

**Comment by gaelj** [comment]
So I take out the color mixer of the GUI and only leave the option of CLI to anyone who wants to customize the palette ?
I admit it seemed cool when I was playing with it but a

**Comment by skaman82** [comment]
"So I take out the color mixer of the GUI and only leave the option of CLI to anyone who wants to customize the palette ?" 
I think this is a good idea

**Comment by skaman82** [comment]
Both bugs I mentioned are fixed now! It works like a charm.

**Comment by gaelj** [comment]
@skaman82 - great. This isn't ready for merge yet, I have to remove the Battery function related code as it's not part of cleanflight officially.

**Comment by skaman82** [comment]
@gaelj ok, will merge this after the new LED cleanup and new stuff (like larson scanner) is merged into firmware

**Comment by skaman82** [comment]
@gaelj https://github.com/cleanflight/cleanflight/pull/2160 needs some work and testing - then it will be hopefully merged for 1.14

**Comment by gaelj** [comment]
I squashed all commits. This should now be ready to merge, unless anyone wants to test or review it any further ?

@skaman82, about merging, my opinion is (even though more LED updates are in preparation), CF 1.13.0 introduced important LED changes, so the configurator should reflect those. Not doing so would give users a bad experience, I think.

@hydra what do you think ? Did you try it out ? A little LED-strip play would be a nice rest from the heavy OSD job you are tackling at the moment :wink:

**Comment by skaman82** [comment]
@gaelj agreed, will do some more testing and merge after that if everything works ok

**Comment by skaman82** [comment]
Tested in CF 1.12 and 1.13 on SPracing board - works just fine! Great work @gaelj Looking forward to that larson scanner though :p

**Comment by skaman82** [comment]
Will merge this tomorrow if @hydra has nothing against it!

**Comment by skaman82** [comment]
one small thing: the .tab-led-strip .select should get a 1px boarder (border: 1px solid silver;) . It looks odd when blink is selected (s. screenshot)
bildschirmfoto 2016-06-15 um 00 46 19

**Comment by skaman82** [comment]
I would also add a margin of 15px under this select element

**Comment by gaelj** [comment]
Feel free to clone this branch and do a PR if you want.

**Comment by skaman82** [comment]
Cloning your branch din't work since I have cleanflight forked myself. I'll fix that after the merge

**Comment by gaelj** [comment]
You should try Tortoise Git.

**Comment by skaman82** [comment]
@gaelj see https://github.com/gaelj/cleanflight-configurator/pull/1

**Comment by skaman82** [comment]
thanks @gaelj looking forward to a follow-up PR with support for https://github.com/cleanflight/cleanflight/pull/2160

**Comment by gaelj** [comment]
Thanks @skaman82. Hopefully tomorrow.

**Pull request merged**
