### PR TITLE
Added support to change FC Loop Time via Setup Tab 

### PR DESCRIPTION
**Pull request by tricopterY**
Dependent on cleanflight/cleanflight#641
Also, not sure if this branch needs to be rebased or what - the pid_tuning.html shouldn't be there.
I guess, I used an older branch (may be master) and things were not in sync with current development branch. So, had to match changes in pid_tuning.html.
Still struggling with learning git.

### CODE REVIEW

**Comment by tricopterY** [comment]
x

**Comment by hydra** [comment]
Note sure that the configuration belongs on the setup tab.  I think the configuration tab is a better place for it.  Any chance you could update the PR and move it there?

**Comment by tricopterY** [comment]
Yes - will do.

**Comment by tricopterY** [comment]
@hydra - please review cleanflight/configurator#151

**Pull request closed without merging**
